server: # 修改访问端口和拦截路径
  port: 11001
  servlet:
    path: "/"
    context-path: /Editor
logging: # 控制日志级别
  level:
    com.my: debug
    # org.springframework: debug
spring: # 配置数据源信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/travel
    username: root
    password: 123
#mybatis:
#  type-aliases-package: com.my.pojo # 配置别名
  # mapper-locations: mapper/*.xml # 配置mapper的xml文件所在路径
